### ISSUE TITLE
Hangs in Fedora 23

### ISSUE THREAD

**Issue by akaihola** [lmartinking/webscreensaver#7]
I installed webscreensaver on my Fedora 23 laptop according to the instructions (with the `-url` parameter). When I launch `xscreensaver-demo`, the preview is empty and I see about 10 `webscreensaver` processes started. The XScreensaver window becomes unresponsive and has to be killed.

When run manually from the command line, `webscreensaver -url <url>` works perfectly displaying the web page in a window.

**Comment by akaihola** [comment]
The hanging behavior magically disappeared after I restarted xscreensaver. But I still get no web page rendered in the preview, just a black screen.

**Comment by lmartinking** [comment]
Hey @akaihola I appreciate that you've brought this up. Someone I know had a similar issue many years ago, but it was fixed when they updated their Linux distribution. So in this case, I'm not sure, as Fedora 23 is pretty recent?

Would you mind doing a bit of exploration on this? Try printing out any arguments and command line variables because this is how XScreensaver allows other programs to draw on it.

**Comment by lmartinking** [comment]
Hi @akaihola any word on this?

**Comment by lmartinking** [comment]
(Closing due to age)
